name: docs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
    # The version of Node.js that will be used
          node-version: 18

      - name: Yarn install
        run: yarn

      - name: Build VuePress site
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
